### ISSUE TITLE
Feature Request: Per Panel Query Execution Timeouts

### ISSUE THREAD

**Issue by brycefisher** [grafana/azure-data-explorer-datasource#165]
When using ADX for a large scale event, I'd rather have dashboard queries timeout than continue to consume CPU resources. ADX does allow clients to set per-query timeouts, but it must be done  via the `servertimeout` [client request property](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/request-properties). Relevant documentation: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits

I'd love to have this value exposed per-panel ideally in the "Query options" section:
![Screen Shot 2020-10-02 at 10 51 48 AM](https://user-images.githubusercontent.com/220106/94954045-59543700-049d-11eb-893b-af6b7d35277e.png)

Thanks for your consideration!

**Comment by mckn** [comment]
@brycefisher I really like this idea! Would it help to be able to set this on a datasource settings level? So you basically could set one value for the whole datasource?

I agree that it would be ideal to add it in the query options but currently we don't have a way of extending those options in Grafana which makes this a bit harder to add.

**Comment by brycefisher** [comment]
Hooray! Yeah, I think there would be a lot of value in adding this to the data source settings, even if we couldn't get it per panel. Thanks for considering this request @mckn!

**Comment by chriswue** [comment]
Hm, could somebody chime in what the status on this is? There is a setting in the datasource now but it doesn't seem to get honored since after 30sec we get `Post "https://*******.*******.kusto.windows.net/v1/rest/query": net/http: request canceled (Client.Timeout exceeded while awaiting headers)` even though in the data source the client timeout is set to `300s`

![image](https://user-images.githubusercontent.com/903928/129653238-c77fe171-cb67-43e4-9fdd-fa011c328446.png)

**Comment by vickyyyyyyy** [comment]
Looks like we were able to help with adding the timeout on the datasource level. For the original feature request to add on the query level, we can’t see us prioritising this any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
