### ISSUE TITLE
Using Monaco editor (with web workers) in custom datasource plugin

### ISSUE THREAD

**Issue by dkozar** [grafana/azure-data-explorer-datasource#219]
Hi,

We've built the custom data source plugin and we'd like to use Monaco as its query editor.

We've already built the editor as React component, wrapping [react-monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor).

The editor calls the API for contextually fetching a vast number of auto-suggestions. It uses **web workers**, so is needs a special **Webpack configuration** for building those workers. Could this be accomplished with data source plugin, and how?

Thanks,

Cc @joshhunt, who seems to be working with Monaco in Azure Monitor plugin (https://github.com/grafana/grafana/issues/30794).

Danko

**Comment by joshhunt** [comment]
Hey @dkozar - as since discussed elsewhere, our first-party approach is to use `CodeEditor` from `@grafana/ui`, which wraps `react-monaco-editor`. If the `CodeEditor` API doesn't expose the right functionality or hooks yet, we can add that in - as you mentioned I'm interested in improving this for KQL for Azure Monitor plugin (and then eventually back to this ADX plugin).

I'm not too familiar with Monaco, and Web Workers + Webpack, so im not sure what the changes would look like,. but bundled core plugins (plugins in the grafana/grafana repo) use the Grafana webpack config, so we would prefer to make generic changes to that config to support features that can be used by the whole codebase. *External* plugins can use whatever webpack config or bundler they want, but typically they'll use config provided by [`@grafana/toolkit`](https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/config/webpack.plugin.config.ts). Generic contributions/changes are accepted for this, but understandably we won't have plugin-specific config here.

We're very interested in improving the KQL editor experience across both the Azure Monitor and ADX plugins, so please let us know how you go, and if you have any questions. Eventually I'll work on this for the Azure Monitor plugin rework, so it would be great to make sure this experience is as consistent as possible :smile:

**Comment by dkozar** [comment]
Hi @joshhunt! Our editor unfortunatelly doesn't deal with KQL but another type of language. The logic (lexer/parser) has already been built into our editor, and this logic interacts with the API (it dynamically fetches names of resources). So I'm not sure if it could be built in generic fashion, as it's fully custom, and not applicable for general audience.

**Comment by joshhunt** [comment]
Ahhh, makes sense.

What are the webpack config changes needed? I'm not too familiar with web workers, but if it's just an additional loader, could you use the `loader-name!` syntax in the import statement? Or the `import()` function for lazy-loading a module? Or perhaps even `file-loader!./worker.js`? Or, the new Webpack 5 web-worker support could be helpful? (grafana and @grafana/toolkit still uses webpack 4, but we want to upgrade to 5 "soon").

For external plugins you could make your own build script and webpack config (i would base it on the one in @grafana/toolkit), but this would be a last resort - you would be on your own, its not documented, and we can't really provide support for this atm.
