### ISSUE TITLE
Differences in Query Results Between ADX and Grafana

### ISSUE THREAD

**Issue by savastosic** [grafana/azure-data-explorer-datasource#330]
**What happened**:
This might not be a bug. 

Certain queries done in the ADX query editor will return different results when run in Grafana. In the screenshots below, you can see that ADX natively splits the visualization by tag name, whereas Grafana will group them all together as one trend.

**What you expected to happen**:
The intent is to have a quick and easy way to plot a series across a group of assets. 
In my example, plotting all tags with "OilPres" in the tagname. Another could be plotting all speed tags for a particular location, or a certain asset type, and so on. 

I can achieve the intended result by using multiple statements in the query builder, but that is a long and tedious process. Any other way to quickly split the trend would be appreciated. 

**Screenshots**

Query run in ADX query builder: 
![image](https://user-images.githubusercontent.com/90868835/157551762-b5e1da89-ea3f-441e-b0ff-3c07d57fd1fb.png)

Query run in Grafana: 
![image](https://user-images.githubusercontent.com/90868835/157552044-2c416fef-5a44-473d-b0fa-04d5d399d97c.png)

**Comment by sunker** [comment]
Thanks for creating this issue @savastosic. 

It's not clear from your screen shoots, but I'm assuming your have select Format as `Time series` in Grafana? 

As you know, the Kusto function [render](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator?pivots=azuredataexplorer) allows you to specify how to visualize results from a query. Since grafana supports many different data source plugins, we can't let the query language determine _how_ to render results - that is done in the panel edit mode. 

Results returned by SQL data bases, or _SQL-like_ data bases such as ADX, normally return data in narrow format. When format as `TimeSeries` is selected, Grafana will detect the narrow format and convert it into a so called _wide format_. Basically it will create on time series per combination of date column/float column and string columns will be represented as labels. You can read more about that in our [documentation](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/#long-format). 

I'm not an expert at KQL, but I think what you want to do could be achieved by grouping (think it's called summarize in KQL) on `v_double`. If not, you can also play around with [transformations](https://grafana.com/docs/grafana/next/panels/transform-data/) which will allow you to reorganize fields etc.
