### ISSUE TITLE
On-Behalf-Of feature should be under a feature flag

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#359]
The On-Behalf-Of feature has a few unresolved edge cases:
* It won't work when AAD environment of Grafana (and thus of user's ID token) is different than Azure environment of the datasource (ADX cluster).
* It won't work when configured app client doesn't have consent to access the service because there's no ability for interactive consent flow.
* It cannot work when Grafana uses non-AAD authenticaton method but UI doesn't reflect it.

Considering this I would put On-Behalf-Of under a feature flag until a more complete solution available.

This way users who well understand the shortcomings would be able to explicitly enable it for their particular scenario but it wouldn't confuse other users until it's polished.

**Comment by sunker** [comment]
It's already stated in the [docs](https://github.com/grafana/azure-data-explorer-datasource/blob/main/doc/on-behalf-of.md) and in the ds configuration ui that this feature is in beta so I'm not sure that's necessary. 

Since the OBO feature in ADX is under a beta flag, we're allowed to make changes to how it behaves and how it's being used. 

While adding support for the edge cases you've described, it might be possible to address it in a few different ways:
1) in a custom middleware in the ADX plugin
2) a part of the Azure middleware in the Azure SK
3) a generic user auth feature in Grafana (discussed [here](https://github.com/grafana/grafana/discussions/39701)) 

I'm curious to hear your thoughts on this @kostrse.

**Comment by kostrse** [comment]
> It's already stated in the [docs](https://github.com/grafana/azure-data-explorer-datasource/blob/main/doc/on-behalf-of.md) and in the ds configuration ui that this feature is in beta so I'm not sure that's necessary.

@sunker could you please give details how does "beta flag" work? Is it something that can be switched on/off in Grafana configuration?

For Azure Grafana service we need this OBO toggle to not be available for users, since it doesn't work there.
It should be something like a feature toggle which we could set in Grafana config.

**Comment by yaelleC** [comment]
After discussion with the team, it seems only ASML is using the feature so the default state will be disabled.

**Comment by yaelleC** [comment]
Update :

- Grafana PR for Feature flag creation : [#49476](https://github.com/grafana/grafana/pull/49476)
- PR for Frontend changes to hide toggle in ADX : #387

Unfortunately: 
Turns out that an external plugin’s backend cannot use Grafana feature flag value :disappointed: , so as it stands, new data sources will not have OBO feature (as no way to enable it in the Config editor) but any plugin that was created enabling it would still be using it :disappointed: .

I’ve let my thoughts for a way forward on the ADX PR:

1. Ideal if possible: I wonder if we can pass the onBehalfOf = false from the frontend when executing the query?
2. Less user friendly: I add code in the config editor (maybe [here](azure-data-explorer-datasource/src/components/ConfigEditor/ConnectionConfig.tsx)) to check the feature flag value. Meaning users would have to open and save the data source for the change to be applied in the data source jsonData

@taleena  as I’m away until next Monday , if Azure need the flag this week then someone should probably pick up where I left off (maybe @andresmgot  has some bandwidth?). If it’s not that time sensitive, I’ll pick it up first thing on Monday.

**Comment by kostrse** [comment]
Since standard feature flags seems like cannot be passed to external datasources, we could use `azsettings.AzureSettings` structure for that.

We can add OBO switch into `[azure]` configuration section ([here](https://github.com/grafana/grafana/blob/bb4a834ee349a423999299d268bafa96ee79676a/conf/sample.ini#L611)):
```ini
[azure]
managed_identity_enabled = true

# Enable/disable On-Behalf-Of authentication using AAD client configured in a datasource
datasource_client_obo_enabled = false
```
This configuration section parsed [here](https://github.com/grafana/grafana/blob/bb4a834ee349a423999299d268bafa96ee79676a/pkg/setting/setting_azure.go#L5) into `azsettings.AzureSettings` structure.

We will need to extend the `azsettings.AzureSettings` in [github.com/grafana/grafana-azure-sdk-go/azsettings/settings.go](https://github.com/grafana/grafana-azure-sdk-go/blob/main/azsettings/settings.go) with additional boolean fiend and then update the [github.com/grafana/grafana-azure-sdk-go](https://github.com/grafana/grafana-azure-sdk-go) package in Grafana.

We need to do it before release of Grafana 9.0.

**Comment by andresmgot** [comment]
I think that we are fine just with the frontend changes.

> but any plugin that was created enabling it would still be using it

Note that the goal of this issue is to hide the feature for environments that won't work in any case (e.g. AMG, because of the issues listed above) so if any existing data source already enabled it, it won't work anyway.

**Comment by andresmgot** [comment]
> We need to do it before release of Grafana 9.0.

Note that since this is an external plugin, we can release anytime (we don't need to bind to Grafana releases).

**Comment by kostrse** [comment]
> Note that since this is an external plugin, we can release anytime (we don't need to bind to Grafana releases).
If we need to introduce a new setting, then it needs to be shipped with Grafana.

**Comment by andresmgot** [comment]
Right, but I think it's fine to skip the setting modifications and simply do the frontend changes. WDYT?

**Comment by yaelleC** [comment]
> so if any existing data source already enabled it, it won't work anyway.

If we hide the frontend toggle they will have to delete the broken data source and re-create one as they will have no way of disabling OBO. 

(Unless we add a check for that in the frontend to show the toggle when editing a data source that has it enabled).

**Comment by andresmgot** [comment]
> If we hide the frontend toggle they will have to delete the broken data source and re-create one as they will have no way of disabling OBO.
> 
> (Unless we add a check for that in the frontend to show the toggle when editing a data source that has it enabled).

My suggestion for that is to disable OBO if they edit the datasource: https://github.com/grafana/azure-data-explorer-datasource/pull/387#discussion_r881392947

**Comment by kostrse** [comment]
Feature flag will work as a workaround for Azure Managed Grafana.

But my opinion is that OBO should be under a proper settings switch and disabled by default, as Managed Identity does.
OBO doesn't work out of box and user needs to read documentation to make it working, so it's not a feature to enable by default.

When we consider moving the backend implementation to Grafana Azure SDK, it will definitely need to go under a switch. It's just matter of time when to introduce this switch.

**Comment by andresmgot** [comment]
It probably makes sense to promote the feature from a feature flag to the Azure config once it's stable.

**Comment by kostrse** [comment]
Thanks, tested works well.
