### ISSUE TITLE
Cluster URL with slash appended would get "404 Not Found" error when saving configuration

### ISSUE THREAD

**Issue by zhichli** [grafana/azure-data-explorer-datasource#373]
**What happened**:
The ADX data source had been working for some time and suddenly stopped working (queries failed) without any configuration changes and the data source configuration settings UI page returned ```Azure query unsuccessful: Azure HTTP "404 NotFound"``` when trying to reload the schema. We actually found a weird mitigation for this issue: when the appending slash ```/``` in the ```Cluster URL``` was removed, the data source started working without the 404 error; adding the slash back would get the 404 error back. More confusingly, this issue only happened to that single particular ADX data source, and there were multiple other ADX data sources set up in the same Grafana instance with the appending slash in their ```Cluster URL``` settings, and they all worked either with or without the slash.
![image](https://user-images.githubusercontent.com/57812115/166297453-2a95e5c8-edfa-43da-87ac-58e45a0978bb.png)

**What you expected to happen**:
For both cases with and without the appending slash in the ```Cluster URL``` value, the ADX data source should work.

**How to reproduce it (as minimally and precisely as possible)**:
for a working ADX data source configuration, try to append a slash ```/``` to the cluster URL and you should see the following error when saving it.
![image](https://user-images.githubusercontent.com/57812115/166298612-db2e3cc8-516c-482a-88a1-04e99fc89f0f.png)

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version: 8.4.5
- Plugin version: 3.7.1
- OS Grafana is installed on: linux
- User OS & Browser: Chrome
- Others:

**Comment by zhichli** [comment]
@taleena

**Comment by taleena** [comment]
Per feedback this appears to be a regression and means that users are seeing broken experiences.

**Comment by sarahzinger** [comment]
@zhichli thanks for reporting your issue! Unfortunately I'm having trouble recreating it. So far I've:
- loaded Grafana 8.4.5 and ADX 3.7.1 
- tried re-saving a working config and did not see any issues
- I then tried appending a `/` at the end of my cluster url and also did not see issues

Do you have any additional data about what happened to trigger this? For example were you updating the plugin or grafana when this started happening?

One thing I can do to trigger the 404 is if I add an endpoint to my cluster url that I know does not exist for example:
- I'll append `/non-existant-url` to the cluster url
- and then I try `Save and Test` and see the 404 error
- and then if I remove `/non-existant-url` but do not click `Save and Test` again and instead click `reload schema` and see that the 404 error remains, I assume because we are trying to reload the schema with the old data
- when I click `Save and Test` to save the datasource without the non existent url, it seems to work fine for me.

Is it possible that this is was the bug you ran into or does it feel unrelated? If so perhaps we can make a ticket to save the datasource before running `reload schema`. 

Also if you have any information from the network tab that might also help us in recreating the error. Thanks so much

**Comment by zhichli** [comment]
@sarahzinger thanks much for looking into it! We did see this issue for one particular instance but unfortunately we could not reproduce it lately even on our side as I confirmed with the original reporter. It could be a server side transient issue rather than client side issue in the plugin. I think we can close this issue for now. cc @taleena
