### ISSUE TITLE
Ignore generic HTTP settings for Azure cloud endpoints

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#554]
`instanceSettings.HTTPClientOptions()` allow to inherit generic HTTP settings for datasource.
While this features allows user to customize authentication and HTTP request, it should not be used for Azure cloud endpoints.

Cloud endpoints have predefined set of capabilities/authentication methods which can be supported by the datasource and user should not customize HTTP requests to Azure endpoints.

**Comment by aangelisc** [comment]
Hi @kostrse, the default `HTTPClientOptions()` also sets various defaults on the HTTP client utilised in datasources and ensures various settings are standardised. 

I appreciate that users shouldn't modify requests to the Azure endpoints, however if a user were to customise the request I'm sure the additional headers would be ignored by the Azure endpoints? Please correct me if I'm wrong on this. Otherwise, we will not be removing the default HTTP client settings.

**Comment by aangelisc** [comment]
As mentioned we'd need the `HTTPClientOptions` to remain as they're used to configure internal middlewares and functionality. Closing this and if it's still an issue we can pick this up offline and discuss a solution.
