### ISSUE TITLE
Support Azure OpenAI

### ISSUE THREAD

**Issue by asimpson** [grafana/azure-data-explorer-datasource#602]
[Relevant docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line&pivots=rest-api)

High-level tasks:

- [x] reach out to Azure to get access for testing and development
- [ ] make URL field configurable since the URL changes based on the deployment of the model in Azure. We'll need two pieces:
  - Deployment name
  - Endpoint, e.g. `https://docs-test-001.openai.azure.com/`

![image](https://github.com/grafana/azure-data-explorer-datasource/assets/1048831/e34e27e3-67f6-4ac0-a39c-2c37c0535b93)

Related to #584 

### Discussed in https://github.com/grafana/azure-data-explorer-datasource/discussions/601

<div type='discussions-op-text'>

<sup>Originally posted by **vidommet** July 27, 2023</sup>
Current OpenAI support only allows OpenAI key. Please expand that to use Azure's OpenAI instances and API keys</div>

**Comment by jtheory** [comment]
If you're ready to switch over to `grafana-llm-app` support for all your LLM API needs :sparkles: , Azure support is now stable over there -- tbh, partly driven by knowing you wanted the option. Plus it turned out to be pretty straightforward.

Let us know when when you're picking that up (happy to help), **or** if there are any blockers / concerns.

Incident Auto-summary migrated over by keeping dual support for now -- if grafana-llm-app is configured, use it, otherwise check for local LLM config -- and will drop the local config path in a future iteration.

**Comment by asimpson** [comment]
@jtheory :tada: Amazing, thanks for letting me know! :trophy:

**Comment by asimpson** [comment]
Fixed in https://github.com/grafana/azure-data-explorer-datasource/pull/699
