### ISSUE TITLE
Visual Query Editor

### ISSUE THREAD

**Issue by daniellee** [grafana/azure-data-explorer-datasource#91]
Creating a visual query editors for other data sources like MySQL or InfluxDB would help new users get started with ADX without having to know KQL well. Even for experienced users, having a wizard/visual query editor would aid in writing queries that return data in the correct format for graphing.

Here are some early designs but need to research the following topics more:
- how simple/complex should the query builder be to cover 80% of queries? Should it be a very simple editor with a few dropdowns (like the sql query editors)? Or should it be possible to build more expressive queries?
- How important is the education aspect of showing the KQL queries to users so that they can learn to write raw KQL queries themselves?
- Which terminology should be used - columns or measurements for example

![image](https://user-images.githubusercontent.com/434655/83064913-e0fae680-a062-11ea-9760-e478d154b2a3.png)

Figma sketch: https://www.figma.com/file/J7JWlBHNLOZwqnNUAfIJob/ADX-query-builder?node-id=3%3A198

![image](https://user-images.githubusercontent.com/434655/83065864-78146e00-a064-11ea-9c0b-08296cba955c.png)

**Comment by srclosson** [comment]
Love this. It's really hard to structure a query editor that captures all the use cases a language (especially like kusto) provides, but I suspect the important thing would be to cover 80% of the common cases, and leave the remaining ones back to monaco.

In angular we had a "switch between" view. Is that no longer going to be a thing? As I see a more hybrid approach here.

**Comment by daniellee** [comment]
@srclosson I think we will keep the switch to raw mode. The latest design looks like it will be simpler than these initial designs.

**Comment by erikbos** [comment]
Please do not remove the raw mode.. we use the ADX plugin quite a bit with complex queries (and sometimes functions as well) A visual editor would likely not be handle that level of query complexity.

**Comment by gilkgit** [comment]
I agree with erikbos, Please do not remove the raw mode. we anyway work with Kusto Explorer and copy paste the queries since the ADX plugin + Chart updating is painfully slow to the point where it's unusable to edit queries in most scenarios.

I'd be happy if the Raw mode could be set as the default editor (maybe by customization), since the experience is already very "mouse clicky" as is.

For us the visual query editor is anyway not a main usage scenario.
Our personas who use Grafana are proficient with ADX syntax.
I'd be happy if it could be hidden from presentation (by customization), since I see how this feature (which might be useful to people who just started using ADX) will bring in negative attitude by people who would feel that it flags the ADX plugin as a tool for absolute beginners.

**Comment by mckn** [comment]
I will close this issue since we have shipped a version with this.
